
2022-01-28 03:43:48,075:__main__:
Filename: Invoice Sample 2-Masked sample (2).pdf. Error occured in Active Learning table.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/start_exacto.py", line 548, in trigger_table
    All_files=os.listdir(Table_text_path)
FileNotFoundError: [Errno 2] No such file or directory: './../output_data/bc251ca7/bar_qr_/Invoice Sample 2-Masked sample (2)/outputs/Table_txt'
