
2022-02-08 07:43:24,133:__main__:
Filename: PNG 2.png. Error occurred in Digitization.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/image_segmentation.py", line 313, in digitize_main
    pdf_path = check_and_convert_extension(pdf_path)
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/multiple_format_to_pdf.py", line 40, in check_and_convert_extension
    pdf_bytes = img2pdf.convert(image.filename)
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 2102, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1483, in read_images
    imgdata, imgformat, default_dpi, colorspace, rawdata
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1189, in get_imgmetadata
    raise AlphaChannelError("Refusing to work on images with alpha channel")
img2pdf.AlphaChannelError: Refusing to work on images with alpha channel

2022-02-08 07:43:24,133:__main__:
Filename: PNG 2.png. Error occurred in Digitization.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/image_segmentation.py", line 313, in digitize_main
    pdf_path = check_and_convert_extension(pdf_path)
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/multiple_format_to_pdf.py", line 40, in check_and_convert_extension
    pdf_bytes = img2pdf.convert(image.filename)
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 2102, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1483, in read_images
    imgdata, imgformat, default_dpi, colorspace, rawdata
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1189, in get_imgmetadata
    raise AlphaChannelError("Refusing to work on images with alpha channel")
img2pdf.AlphaChannelError: Refusing to work on images with alpha channel

2022-02-08 07:43:24,133:__main__:
Filename: PNG 2.png. Error occurred in Digitization.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/image_segmentation.py", line 313, in digitize_main
    pdf_path = check_and_convert_extension(pdf_path)
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/multiple_format_to_pdf.py", line 40, in check_and_convert_extension
    pdf_bytes = img2pdf.convert(image.filename)
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 2102, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1483, in read_images
    imgdata, imgformat, default_dpi, colorspace, rawdata
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1189, in get_imgmetadata
    raise AlphaChannelError("Refusing to work on images with alpha channel")
img2pdf.AlphaChannelError: Refusing to work on images with alpha channel

2022-02-08 08:28:54,461:__main__:
Filename: PNG 2.png. Error occurred in Digitization.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/image_segmentation.py", line 313, in digitize_main
    pdf_path = check_and_convert_extension(pdf_path)
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/multiple_format_to_pdf.py", line 40, in check_and_convert_extension
    pdf_bytes = img2pdf.convert(image.filename)
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 2102, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1483, in read_images
    imgdata, imgformat, default_dpi, colorspace, rawdata
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1189, in get_imgmetadata
    raise AlphaChannelError("Refusing to work on images with alpha channel")
img2pdf.AlphaChannelError: Refusing to work on images with alpha channel

2022-02-08 08:29:00,489:__main__:
Filename: PNG 2.png. Error occurred in Digitization.
Traceback (most recent call last):
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/image_segmentation.py", line 313, in digitize_main
    pdf_path = check_and_convert_extension(pdf_path)
  File "/drive/mnt/pradeep/invoiceProduct_solution/apps/multiple_format_to_pdf.py", line 40, in check_and_convert_extension
    pdf_bytes = img2pdf.convert(image.filename)
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 2102, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1483, in read_images
    imgdata, imgformat, default_dpi, colorspace, rawdata
  File "/data/common/miniconda3/envs/cba_gpu/lib/python3.7/site-packages/img2pdf.py", line 1189, in get_imgmetadata
    raise AlphaChannelError("Refusing to work on images with alpha channel")
img2pdf.AlphaChannelError: Refusing to work on images with alpha channel
